FROM node:latest as build-stage
WORKDIR /app
COPY ./web/package*.json ./
COPY ./.env ./
RUN npm ci
COPY ./web/ .
RUN npm run build

FROM nginx as production-stage
RUN mkdir /app
COPY --from=build-stage /app/dist /app
COPY ./web/nginx.conf /etc/nginx/nginx.conf
